<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5e8334f96c4dc',
        'title' => 'Event info',
        'fields' => array(
            array(
                'key' => 'field_5e8342e3b28d3',
                'label' => 'Description',
                'name' => 'descript',
                'type' => 'text',
                'instructions' => 'Short description of the event',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '90',
            ),
            array(
                'key' => 'field_5e837cc067936',
                'label' => 'Thumbnail',
                'name' => 'thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5e83350d5bd80',
                'label' => 'Date',
                'name' => 'date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'j F',
                'return_format' => 'j F',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5e837f799bae0',
                'label' => 'Entrance',
                'name' => 'entrance',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e8dc987f686b',
                'label' => 'End date',
                'name' => 'end_date',
                'type' => 'date_picker',
                'instructions' => 'If event continues for more than one day, please select end date here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'j F',
                'return_format' => '- j F',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5e8dca27f686c',
                'label' => 'Time',
                'name' => 'time',
                'type' => 'time_picker',
                'instructions' => 'Please select time when the event starts.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'H.i',
                'return_format' => 'H.i',
            ),
            array(
                'key' => 'field_5e8dca7cf686d',
                'label' => 'End time',
                'name' => 'end_time',
                'type' => 'time_picker',
                'instructions' => 'Please select time when the event ends.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'H.i',
                'return_format' => '- H.i',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'evenemang',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
